/* Read-only image analysis: locates the three figures on original chroma-key
 * atlases. Saves only crop/scale metadata; never modifies the image pixels. */
'use strict';
const fs=require('fs'),path=require('path');
const sharp=require(process.env.SHARP_MODULE||'sharp');
async function main(){
 const dir=path.join(__dirname,'../assets/enemies'),out={};
 for(const file of fs.readdirSync(dir).filter(f=>f.endsWith('.png')).sort()){
  const {data,info}=await sharp(path.join(dir,file)).removeAlpha().raw().toBuffer({resolveWithObject:true});
  const frames=[]; const {width:w,height:h}=info;
  const bands=[];let start=-1;
  for(let x=0;x<=w;x++){let on=false;if(x<w)for(let y=3;y<h-3;y++){const i=(x+y*w)*3;if(data[i]+data[i+2]-2*data[i+1]<=285){on=true;break;}}
   if(on&&start<0)start=x;if(!on&&start>=0){if(x-start>30)bands.push([start,x-1]);start=-1;}}
  if(bands.length!==3)throw Error(file+' has '+bands.length+' figure bands instead of three');
  for(let frame=0;frame<3;frame++){
   let x0=w,y0=h,x1=0,y1=0,count=0;
   for(let y=3;y<h-3;y++)for(let x=bands[frame][0];x<=bands[frame][1];x++){
    const i=(x+y*w)*3,r=data[i],g=data[i+1],b=data[i+2];
    if(r+b-2*g>285)continue;
    x0=Math.min(x0,x);x1=Math.max(x1,x);y0=Math.min(y0,y);y1=Math.max(y1,y);count++;
   }
   if(count<1000)throw Error(file+' missing view '+frame);
   // Small margin avoids clipping antialiased toes/fingers at the crop boundary.
   x0=Math.max(0,x0-3);x1=Math.min(w-1,x1+3);y0=Math.max(0,y0-2);y1=Math.min(h-1,y1+1);
   const width=x1-x0+1,height=y1-y0+1;
   frames.push({uv:[x0/w,1-(y1+1)/h,width/w,height/h].map(v=>+v.toFixed(7)),aspect:+(width/height).toFixed(5),bounds:[x0,y0,x1,y1],pixels:count});
  }
  out[path.basename(file,'.png')]={width:w,height:h,frames};
  console.log(file,frames.map(f=>f.bounds.join(',')).join(' / '));
 }
 fs.writeFileSync(path.join(__dirname,'../js/enemy-atlas.js'),'/* Generated by tools/enemy-atlas.cjs from reviewed assets. */\nconst ENEMY_ATLAS = '+JSON.stringify(out,null,2)+';\n');
}
main().catch(e=>{console.error(e);process.exitCode=1});
